name: proof-jobs
static_sites:
- name: web
  source_dir: /
  github:
    repo: Ajalways/proof-jobs-platform
    branch: main
  build_command: npm ci && npm run build
  output_dir: dist
  environment_slug: node-js
